kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/JohnPerks1961/ODO-py.git'
    openshift.io/generated-by: OpenShiftWebConsole
  resourceVersion: '93514'
  name: jlp-py-app1
  uid: df4bd15d-ae8c-4f73-960c-c1054815331d
  creationTimestamp: '2023-06-16T19:22:42Z'
  generation: 4
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2023-06-16T19:35:46Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:app.openshift.io/vcs-ref': {}
            'f:app.openshift.io/vcs-uri': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime': {}
        'f:spec':
          'f:output':
            'f:to': {}
          'f:runPolicy': {}
          'f:source':
            'f:contextDir': {}
            'f:git':
              .: {}
              'f:uri': {}
            'f:sourceSecret': {}
            'f:type': {}
          'f:strategy':
            'f:dockerStrategy':
              .: {}
              'f:dockerfilePath': {}
            'f:type': {}
          'f:triggers': {}
    - manager: openshift-apiserver
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2023-06-16T19:37:58Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:lastVersion': {}
  namespace: jlpproject1
  labels:
    app: jlp-py-app1
    app.kubernetes.io/component: jlp-py-app1
    app.kubernetes.io/instance: jlp-py-app1
    app.kubernetes.io/name: jlp-py-app1
    app.kubernetes.io/part-of: jlp-py-app1
    app.openshift.io/runtime: python-basic
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'jlp-py-app1:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: docker/Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/JohnPerks1961/ODO-py.git'
    contextDir: /
    sourceSecret:
      name: jlpgitpat
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: jlp-py-app1-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: jlp-py-app1-github-webhook-secret
    - type: ConfigChange
  runPolicy: Serial
status:
  lastVersion: 2
